# Auto-generated by frontend-eda-env-setup
# Simulator: <SIMULATOR>
# Template: simulators/<SIMULATOR>.md
# Generated: <TIMESTAMP>
# To regenerate: re-run frontend-eda-env-setup skill

#--------------------------------------------------------------
# Tool Commands
#--------------------------------------------------------------
COMPILE_CMD      = <COMPILE>
COMPILE_COV_CMD  = <COMPILE_COV>
COMPILE_WAVE_CMD = <COMPILE> <DUMP_DEFINE>
RUN_CMD          = <RUN>
RUN_COV_CMD      = <RUN_COV>
RUN_WAVE_CMD     = <RUN> <DUMP_RUNTIME_FLAGS>
COV_REPORT_CMD   = <COV_REPORT>
CLEAN_CMD        = <CLEAN>
WAVE_CMD         = <WAVE>

#--------------------------------------------------------------
# Project
#--------------------------------------------------------------
FLIST    = flist
TOP      = <TOP_MODULE>
SEED    ?= random
LOG_DIR  = logs
BACKUP_DIR = backup

#--------------------------------------------------------------
# Targets
#--------------------------------------------------------------
.PHONY: compile compile_cov compile_wave sim sim_cov sim_wave coverage wave lint clean backup help

compile:
	$(COMPILE_CMD)

compile_cov:
	$(COMPILE_COV_CMD)

compile_wave:
	$(COMPILE_WAVE_CMD)

sim:
	$(RUN_CMD) $(if $(SEED),<SEED_FLAG>$(SEED))

sim_cov:
	$(RUN_COV_CMD) $(if $(SEED),<SEED_FLAG>$(SEED))

sim_wave: compile_wave
	$(RUN_WAVE_CMD) $(if $(SEED),<SEED_FLAG>$(SEED))

coverage:
	$(COV_REPORT_CMD)

wave:
	$(WAVE_CMD)

backup:
	@timestamp=$$(date +%Y-%m-%d_%H-%M-%S); \
	mkdir -p $(BACKUP_DIR)/$$timestamp; \
	for f in *.log $(LOG_DIR)/*.log; do \
		[ -f "$$f" ] && cp "$$f" $(BACKUP_DIR)/$$timestamp/; \
	done; \
	[ -d coverage_txt ] && cp -r coverage_txt $(BACKUP_DIR)/$$timestamp/; \
	echo "Backed up to $(BACKUP_DIR)/$$timestamp"

clean:
	$(CLEAN_CMD)

help:
	@echo "Targets:"
	@echo "  compile      - Compile RTL"
	@echo "  compile_cov  - Compile RTL with coverage"
	@echo "  sim          - Run simulation (SEED=random)"
	@echo "  sim_cov      - Run simulation with coverage"
	@echo "  sim_wave     - Run simulation with waveform dump"
	@echo "  coverage     - Generate coverage report"
	@echo "  wave         - Open waveform viewer"
	@echo "  backup       - Backup logs and reports"
	@echo "  clean        - Remove generated products"
